[2025-09-22T00:40:55.147+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: processamento_silver.products_to_silver manual__2025-09-22T00:40:46.287154+00:00 [queued]>
[2025-09-22T00:40:55.250+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: processamento_silver.products_to_silver manual__2025-09-22T00:40:46.287154+00:00 [queued]>
[2025-09-22T00:40:55.264+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-09-22T00:42:56.628+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): products_to_silver> on 2025-09-22 00:40:46.287154+00:00
[2025-09-22T00:42:56.702+0000] {standard_task_runner.py:60} INFO - Started process 1023 to run task
[2025-09-22T00:42:56.781+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'processamento_silver', 'products_to_silver', 'manual__2025-09-22T00:40:46.287154+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/processamento_silver.py', '--cfg-path', '/tmp/tmp61b8d2w2']
[2025-09-22T00:40:55.627+0000] {standard_task_runner.py:88} INFO - Job 103: Subtask products_to_silver
[2025-09-22T00:40:55.873+0000] {task_command.py:423} INFO - Running <TaskInstance: processamento_silver.products_to_silver manual__2025-09-22T00:40:46.287154+00:00 [running]> on host e833383cbb8e
[2025-09-22T00:40:56.243+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='processamento_silver' AIRFLOW_CTX_TASK_ID='products_to_silver' AIRFLOW_CTX_EXECUTION_DATE='2025-09-22T00:40:46.287154+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-22T00:40:46.287154+00:00'
[2025-09-22T00:40:56.259+0000] {sql.py:276} INFO - Executing: CREATE SCHEMA IF NOT EXISTS silver;

DROP TABLE IF EXISTS silver.olist_products_dataset;

CREATE TABLE silver.olist_products_dataset AS
SELECT
    product_id,
    lower(trim(product_category_name)) AS product_category_name,
    product_name_lenght::INTEGER,
    product_description_lenght::INTEGER,
    product_photos_qty::INTEGER,
    CAST(product_weight_g AS NUMERIC(18,6)) AS product_weight_g,
    CAST(product_length_cm AS NUMERIC(18,6)) AS product_length_cm,
    CAST(product_height_cm AS NUMERIC(18,6)) AS product_height_cm,
    CAST(product_width_cm AS NUMERIC(18,6)) AS product_width_cm
FROM bronze.olist_products_dataset;
[2025-09-22T00:40:56.340+0000] {base.py:83} INFO - Using connection ID '***_db' for task execution.
[2025-09-22T00:40:56.490+0000] {base.py:83} INFO - Using connection ID '***_db' for task execution.
[2025-09-22T00:40:56.521+0000] {sql.py:450} INFO - Running statement: CREATE SCHEMA IF NOT EXISTS silver;

DROP TABLE IF EXISTS silver.olist_products_dataset;

CREATE TABLE silver.olist_products_dataset AS
SELECT
    product_id,
    lower(trim(product_category_name)) AS product_category_name,
    product_name_lenght::INTEGER,
    product_description_lenght::INTEGER,
    product_photos_qty::INTEGER,
    CAST(product_weight_g AS NUMERIC(18,6)) AS product_weight_g,
    CAST(product_length_cm AS NUMERIC(18,6)) AS product_length_cm,
    CAST(product_height_cm AS NUMERIC(18,6)) AS product_height_cm,
    CAST(product_width_cm AS NUMERIC(18,6)) AS product_width_cm
FROM bronze.olist_products_dataset;, parameters: None
[2025-09-22T00:40:57.327+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_namespace_nspname_index"
DETAIL:  Key (nspname)=(silver) already exists.

[2025-09-22T00:40:57.357+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=processamento_silver, task_id=products_to_silver, execution_date=20250922T004046, start_date=20250922T004055, end_date=20250922T004057
[2025-09-22T00:40:57.421+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 103 for task products_to_silver (duplicate key value violates unique constraint "pg_namespace_nspname_index"
DETAIL:  Key (nspname)=(silver) already exists.
; 1023)
[2025-09-22T00:40:57.472+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-22T00:40:57.890+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
