[2025-09-22T00:14:20.868+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: processamento_silver.sellers_to_silver manual__2025-09-22T00:10:23.597638+00:00 [queued]>
[2025-09-22T00:14:20.894+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: processamento_silver.sellers_to_silver manual__2025-09-22T00:10:23.597638+00:00 [queued]>
[2025-09-22T00:14:20.894+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-09-22T00:14:20.928+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): sellers_to_silver> on 2025-09-22 00:10:23.597638+00:00
[2025-09-22T00:14:20.942+0000] {standard_task_runner.py:60} INFO - Started process 474 to run task
[2025-09-22T00:14:20.948+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'processamento_silver', 'sellers_to_silver', 'manual__2025-09-22T00:10:23.597638+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/processamento_silver.py', '--cfg-path', '/tmp/tmp6mt4as3q']
[2025-09-22T00:14:20.954+0000] {standard_task_runner.py:88} INFO - Job 55: Subtask sellers_to_silver
[2025-09-22T00:14:21.082+0000] {task_command.py:423} INFO - Running <TaskInstance: processamento_silver.sellers_to_silver manual__2025-09-22T00:10:23.597638+00:00 [running]> on host e833383cbb8e
[2025-09-22T00:14:21.168+0000] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'sellers_to_silver', field 'sql'. Template: '/opt/***/sql/silver/sellers_to_silver.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/sql/silver/sellers_to_silver.sql
[2025-09-22T00:14:21.170+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2465, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2877, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/sql/silver/sellers_to_silver.sql
[2025-09-22T00:14:21.184+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=processamento_silver, task_id=sellers_to_silver, execution_date=20250922T001023, start_date=20250922T001420, end_date=20250922T001421
[2025-09-22T00:14:21.212+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 55 for task sellers_to_silver (/opt/airflow/sql/silver/sellers_to_silver.sql; 474)
[2025-09-22T00:14:21.246+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-22T00:14:21.276+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
